#pragma once

#include "XorStr.h"

#define RUST_OBJECTMANAGER 0x15FC218

#define OBJECTMANAGER_TAGGEDLISTFIRST 0x0
#define OBJECTMANAGER_TAGGEDLIST 0x8
#define OBJECTMANAGER_ACTIVELIST 0x18
#define OBJECTMANAGER_ACTIVELISTLAST 0x10

#define TAGGEDLIST_NEXTTAGGEDENT 0x8
#define BASEENT_GAMEOBJECT 0x10

#define GAMEOBJECT_OBJECTCLASS 0x30
#define GAMEOBJECT_OBJECTNAMEPTR 0x60
#define GAMEOBJECT_TAG 0x54

#define OBJECTCLASS_TRANSFORM 0x8
#define OBJECTCLASS_ENTITYPTR 0x18

#define ENTITYPTR_BASEENT 0x28

#define TRANSFORM_VISUALSTATE 0x38

#define VISUALSTATE_POSITION 0xb0

#define ENTITYPTR_MATRIX 0x2E4

#define BASEENT_NAME 0x4B0
#define BASEENT_MODEL 0x80

#define MODEL_TRANSFORM 0x40

#define TRANSFORM_BONE 0x20

#define BONE_WORLD 0x10